CREATE DATABASE IF NOT EXISTS todosdb;

CREATE USER IF NOT EXISTS 'todo'@'localhost' IDENTIFIED BY 'nano123!';

GRANT SELECT, INSERT, UPDATE, DELETE PRIVILEGES ON todosdb.* TO 'todo'@'localhost';

FLUSH PRIVILEGES;